console.log('This is the index file for the apps directory. 113123')
console.log('You can add your application logic here. 123123')
console.log('You can add your application logic here. 1sdsf')
console.log('some changes 3')
console.log('user facing1 ')
console.log('user facing')